version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: radar-mysql
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=php
        - MYSQL_DATABASE=php
        - MYSQL_USER=php
        - MYSQL_PASSWORD=php
      ports:
        - "8001:3306"

    redis:
      image: redis:alpine
      container_name: radar-redis
      command: redis-server --appendonly yes --requirepass php
      volumes:
      - ./data/redis:/data
      ports:
        - "8002:6379"

    mailhog:
      image: mailhog/mailhog:latest
      container_name: radar-mailhog
      ports:
        - "8003:1025"
        - "8025:8025"

    redisnodb:
      image: redis:alpine
      container_name: radar-redisnodb
      ports:
        - "8004:6379"

    papercut:
      image: jijiechen/papercut:latest
      container_name: radar-papercut
      ports:
        - "8005:25"
        - "37408:37408"
