version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: radar-mysql
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD="${DB_PASSWORD}"
        - MYSQL_DATABASE="${DB_DATABASE}"
        - MYSQL_USER="${DB_USERNAME}"
        - MYSQL_PASSWORD="${DB_PASSWORD}"
      ports:
        - "8001:3306"


    redis:
      image: redis:alpine
      container_name: radar-redis
      command: redis-server --appendonly yes --requirepass radar
      volumes:
      - ./data/redis:/data
      ports:
        - "8002:6379"

    mysqltest:
      image: mysql:8.0
      container_name: radar-mysql-test
      volumes:
        - tmpfs:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD="${DB_PASSWORD}"
        - MYSQL_DATABASE="${DB_DATABASE}"
        - MYSQL_USER="${DB_USERNAME}"
        - MYSQL_PASSWORD="${DB_PASSWORD}"
      ports:
        - "8011:3306"

