version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: radar-mysql
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=radar
        - MYSQL_DATABASE=radar
        - MYSQL_USER=radar
        - MYSQL_PASSWORD=radar
      ports:
        - "8001:3306"


    redis:
      image: redis:alpine
      container_name: radar-redis
      command: redis-server --appendonly yes --requirepass radar
      volumes:
      - ./data/redis:/data
      ports:
        - "8002:6379"

