version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: radar-mysql
      volumes:
        - ./data/mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=radar
        - MYSQL_DATABASE=radar
        - MYSQL_USER=radar
        - MYSQL_PASSWORD=radar
      ports:
        - "8001:3306"



